### ISSUE TITLE
Project wiring?

### ISSUE THREAD

**Issue by slowtoaccept** [nootropicdesign/lora-weather-station#1]
Can you provide the project wiring diagram and the code for the Anarduino MiniWireless module?
Is it WeatherSensor.ino? TH02 is connected directly to it?

Do you upload code directly to it ..using a FTDI TTL-USB converter? 
 
How's the big electrolytic wired,..across the solar panel output? 

It appears that you are using a ESP8266, based module for the base station? What's used on the Weather Station? Is it just to power the MiniWireless?

**Comment by nootropicdesign** [comment]
The details of the project are here:
https://nootropicdesign.com/projectlab/2017/09/03/solar-powered-lora-weather-station/

The Anarduino Miniwireless is just a small Arduino compatible board that you upload to using an FTDI adapter. Yes, the sensor is connected to it. There is also a Adafruit LiPo charging board (with the big capacitor) on the weather station and this provides power to the Anarduino board.

**Comment by slowtoaccept** [comment]
Thanks for a great project. Learned a lot. And your Project Lab is inspiring. Here's the Adafruit charger link missing from your project description: https://www.adafruit.com/product/390. They have several models.
